# Generated by Django 5.1 on 2024-08-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=100, verbose_name='First name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last name')),
                ('gender', models.BooleanField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=100)),
                ('sslc_marks', models.FloatField(blank=True, null=True)),
                ('plus_two_marks', models.FloatField()),
                ('account', models.PositiveBigIntegerField()),
                ('university_reg_no', models.CharField(max_length=50, unique=True)),
                ('avail_hostel', models.BooleanField()),
                ('avail_bus', models.BooleanField()),
                ('parent_phone', models.CharField(max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('address_line', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': '',
            },
        ),
    ]
